version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=admin
    #      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongodb-cryptonate
    volumes:
      - ~/mongo:/data/db
    networks:
      - mongo-compose-network
  cryptonate:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app # telling to reference current local directory : container directory app (which was copied when image was created)
      - /app/node_modules
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb
    links:
      - mongodb
networks:
  mongo-compose-network:
    driver: bridge
