### Project Form CREATE

POST http://localhost:4000/api/v1/project/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="angry_lolli.jpeg"
Content-Type: image/jpeg

< ../../angry_lolli.jpeg
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="orgName"

org
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="projectName"

Third Project
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="projectSubTitle"

Subtitle
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="category"

Animal
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="summary"

This is a summary
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="solution"

this is a solution
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="goalAmount"

1234.00
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="totalSaved"

14.66
--WebAppBoundary--


### GET project

POST http://localhost:4000/api/v1/project HTTP/1.1
content-type: application/json

{
  "orgName": "org",
  "projectName": "Third Project"
}


### GET image

GET http://localhost:4000/api/v1/images/bb35b8f7d8212fb9596524f4245e0bee HTTP/1.1
Content-Type: application/json


### GET all projects

GET http://localhost:4000/api/v1/project/explore HTTP/1.1
content-type: application/json


### GET projects by search term or category

GET http://localhost:4000/api/v1/project/explore/search?category=Animal&search=Third+Project HTTP/1.1
content-type: application/json





