
### REGISTER USER

POST http://localhost:4000/api/v1/user HTTP/1.1
content-type: application/json

{
  "username": "donor2",
  "password": "password",
  "email": "donor2@gmail.com",
  "role": "donor"
}

### LOGIN USER

POST http://localhost:4000/api/v1/user/login HTTP/1.1
content-type: application/json

{
  "username": "donor2",
  "password": "password",
  "role": "donor"
}

### GET LOGGEDIN

POST http://localhost:4000/api/v1/user/loggedIn HTTP/1.1
content-type: application/json

{
  "username": "donor2",
  "role": "donor"
}

### Logout User

POST http://localhost:4000/api/v1/user/logout HTTP/1.1
content-type: application/json

{}

### Register Organization

POST http://localhost:4000/api/v1/user HTTP/1.1
content-type: application/json

{
  "username": "org",
  "password": "password",
  "email": "org@gmail.com",
  "role": "organization"
}

### Organization Authentication Form CREATE

POST http://localhost:4000/api/v1/user/submitOrgForm HTTP/1.1
content-type: application/json

{
  "orgId": "org",
  "name": "org",
  "EIN": "123456",
  "category": "animal",
  "email": "org@gmail.com",
  "phone": "123456789",
  "location": "Stony Brook",
  "website": "org.com",
  "approved": "false"
}

### Organization Authentication Form UPDATE

POST http://localhost:4000/api/v1/user/updateOrgForm HTTP/1.1
content-type: application/json

{
  "orgId": "org",
  "name": "organization updated",
  "website": "org.com"
}

### Organization Authentication Form GET

POST http://localhost:4000/api/v1/user/orgForm HTTP/1.1
content-type: application/json

{
  "orgId": "org"
}


### Project Form CREATE

POST http://localhost:4000/api/v1/project/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="angry_lolli.jpeg"
Content-Type: image/jpeg

< ../../angry_lolli.jpeg
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="orgName"

org
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="projectName"

New Project
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="projectSubTitle"

Subtitle
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="category"

Animal
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="summary"

This is a summary
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="solution"

this is a solution
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="goalAmount"

1234.00
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="totalSaved"

12.00
--WebAppBoundary--


### GET project

POST http://localhost:4000/api/v1/project HTTP/1.1
content-type: application/json

{
  "orgName": "org",
  "projectName": "New Project"
}
