### REGISTER USER 

POST http://localhost:4000/api/v1/user HTTP/1.1
content-type: application/json

{
  "username": "donor2",
  "password": "password",
  "email": "donor2@gmail.com",
  "role": "donor"
}

### LOGIN USER

POST http://localhost:4000/api/v1/user/login HTTP/1.1
content-type: application/json

{
  "username": "donor2",
  "password": "password",
  "role": "donor"
}

### GET LOGGEDIN

POST http://localhost:4000/api/v1/user/loggedIn HTTP/1.1
content-type: application/json

{
  "username": "donor2",
  "role": "donor"
}

### Logout User

POST http://localhost:4000/api/v1/user/logout HTTP/1.1
content-type: application/json

{}

### Register Organization

POST http://localhost:4000/api/v1/user HTTP/1.1
content-type: application/json

{
  "username": "org",
  "password": "password",
  "email": "org@gmail.com",
  "role": "organization"
}

### Organization Authentication Form Submit

POST http://localhost:4000/api/v1/user/orgForm HTTP/1.1
content-type: application/json

{
  "orgId": "org",
  "name": "org",
  "EIN": "123456",
  "category": "animal",
  "email": "org@gmail.com",
  "phone": "123456789",
  "location": "Stony Brook",
  "website": "org.com",
  "approved": "false"
}

### Organization Authentication Form Update

POST http://localhost:4000/api/v1/user/updateOrgForm HTTP/1.1
content-type: application/json

{
  "orgId": "org",
  "name": "organization updated",
  "website": "org.com"
}